process:
	- python process_raw.py antony-and-cleopatra.txt
	- python process_raw.py asyoulikeit.txt
	- python process_raw.py errors.txt
	- python process_raw.py hamlet.txt
	- python process_raw.py juliuscaesar.txt
	- python process_raw.py lear.txt
	- python process_raw.py macbeth.txt
	- python process_raw.py measure-for-measure.txt
	- python process_raw.py merchant.txt
	- python process_raw.py msnd.txt
	- python process_raw.py othello.txt
	- python process_raw.py richardii.txt
	- python process_raw.py richardiii.txt
	- python process_raw.py romeojuliet.txt
	- python process_raw.py tempest.txt
	- python process_raw.py twelfthnight.txt
	- python process_raw.py winterstale.txt


